---
- name: install packages
  command: "/opt/bin/opkg install {{ item }}"
  register: command_result
  changed_when: command_result.stdout is not search("is up to date.")
  with_items:
    - nano
    - git
    - htop
    - lsblk
    - lscpu
#python is already installed by setup_entware.sh
